### ISSUE TITLE
Missing Seed(s)

### ISSUE THREAD

**Issue by BIGboogers** [bimbam2103/xsecd#1]
Hi Christian,

xsecd.exe Error: "[WARN] Could not register as seed" 

Not a programmer, but could this be the reason for the error message?

Please check:

Line 26 of xsecd.py

seeds = [ ]

**Comment by bimbam2103** [comment]
Hello BIGboopers... Thanks for testing the xsec daemon.

No. Line 26 is just to define the variable. If your node cannot register with the master node there could be two possible reasons:

1. You do not have a correct internet connection (i think this is not the reason)
2. You do not have enabled port forwarding from your router/firewall to the daemon

By default if your node wants to register the masternode trys to connect to your node.. If this does not work the masternode returns an "invalid" which means the register does not work.

Greetings
